In [4]:
import numpy as np

In [5]:
n = np.array([-6, 2, 5])
a = np.array([
    [-7, 4, 10],
    [5, 8, 2],
    [-1, 0, 9]
])
b = np.linalg.inv(a)
n_column = n.reshape(3, 1)
m = b @ n_column
print("Прообраз точки n:")
print(m) 

Прообраз точки n:
[[ 1.41176471]
 [-0.81045752]
 [ 0.7124183 ]]


In [6]:
print("Проверка:")
print(a @ m) 

Проверка:
[[-6.]
 [ 2.]
 [ 5.]]


In [7]:
a = np.array(
 [[0, 17, -2, 6],
  [7, 2, 15, 4],
  [5, -8, 3, 6],
  [0, -12, 4, 7]]
)

t = np.array([8, -4, 1, 15])
s = a @ t.reshape(4, 1)

# Допишите код здесь.
print("Прообраз:")
print(s)
print("Проверка:")
print(np.linalg.inv(a) @ s.reshape(4,1))

Прообраз:
[[ 20]
 [123]
 [165]
 [157]]
Проверка:
[[ 8.]
 [-4.]
 [ 1.]
 [15.]]


## Матрица линейного преоборазования в разных базисах

A=TA 
1
​
 T 
−1

A 
1
​
 =T 
−1
 AT

In [2]:
import numpy as np

a = np.array([
    [7, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]) #матрица преобразорвания в исходном базисе
t = np.array([
    [2, -1, 0],
    [1, 4, 2],
    [-3, -1, -5] # Невырожденная матрица перехода к новому базису
])
s = np.linalg.inv(t) # Обратная матрица матрицы перехода.
print((s @ a @ t).round()) # Матрица нового линейного преобразования с округлением.

[[ 7. -3.  0.]
 [ 0.  1.  0.]
 [-4.  2.  1.]]
