умножение происходит строка - на столбец. AB != BA. Кол-во столбцов A == кол-во строк B

In [1]:
import numpy as np

In [3]:
W = np.array([
    [-15, 2, 0, 4],
    [-8, 1, 10, 5], 
    [6, 9, -4, 3],
    [-1, 5, 21, 6]
])

K = np.array([
    [0, -5, 1, 3],
  [0, 2, 4, 0],
  [-15, 3, 7, 2],
  [9, -6, 3, 12]
])

Y = np.array([
    [9, -7],
  [2, 31], 
  [0, 4], 
  [-1, -6]
])

In [4]:
print("Произведение WK:")
print(W @ K)
print()
print("Произведение YW:")
print('no')
print()
print("Произведение KY:")
print(K @ Y)
print()
print("Произведение KW:")
print(K @ W)

Произведение WK:
[[  36   55    5    3]
 [-105   42   81   56]
 [  87  -42   23   46]
 [-261   42  184  111]]

Произведение YW:
no

Произведение KY:
[[ -13 -169]
 [   4   78]
 [-131  214]
 [  57 -309]]

Произведение KW:
[[ 43  19   9  -4]
 [  8  38   4  22]
 [241  46  44 -12]
 [-81  99 180  87]]


#### Практика

In [7]:
A = np.array([
            [-1, 0, 5],
            [2, -3, 1],
            [0, 4, -6]
            ])

B = np.array([
    [0, 3, -2],
    [-5, -1, 3],
    [-7, 1, 4]
])

print((B @ A).reshape(1, 9))

[[  6 -17  15   3  15 -44   9  13 -58]]


In [8]:
K = np.array( [[4, 8, 0, 12, 3],
                [2, 8, -6, 9, 1],
                [7, 6, 1, 0, 10]])


S = np.array([[1, 6, 9],
              [2, 15, 5],
              [8, 0, 12],
              [4, 7, 3],
              [1, 6, 14]])
 
R = np.array([[8, 0, 1, 3, 9],
  [-2, 7, 9, 1, 4],
  [6, 3, 6, -7, 1],
  [0, 12, 6, 3, 7],
  [2, 8, 12, 21, 5]])
 


# допишите код здесь
print("Произведение KS:")
print(K@S)
print()
print("Произведение RS:")
print(R@S)
print()
print("Произведение RKS:")
print('no')
print()
print("Произведение SKR:")
print(S @ K @ R)

Произведение KS:
[[ 71 246 154]
 [  7 201  27]
 [ 37 192 245]]

Произведение RS:
[[ 37 123 219]
 [ 92 124 184]
 [ 33  38 134]
 [ 91 243 239]
 [203 309 335]]

Произведение RKS:
no

Произведение SKR:
[[ 448 2273 2491 2813 2081]
 [-116 3383 2863 2948 2704]
 [1016 3292 3716 3712 2992]
 [  60 2349 2025 1894 1866]
 [ 798 2898 3426 3963 2771]]


In [4]:
#КР
A = np.array([[-2, 6, 4],
             [1, 0, 5],
             [0, 4, 2]])
B = np.array([[-6, 0, 0],
             [0.5, 1, 4],
             [-2, 1, 2]])
C = np.array([[0.5, 3, 1],
             [-1, 2, 8],
             [2.5, 4, 0]])

A @ C @ B

array([[-99. ,  68. , 180. ],
       [-68.5,  24. ,  94. ],
       [-62. ,  48. , 128. ]])

In [5]:
a = np.array([8, -3, 1, 6])

  
C = np.array([[0, 6, -4, 2],
  [1, 8, 7, -12],
  [5, 0, -2, 8],
  [3, 8, 2, 4]])
   

Z = np.array([[1, 1, -9, 4],
  [2, 8, 4, 6],
  [0, 8, 6, 0],
  [1, 5, -3, 4]])
              
M = np.array([[2, 15, 1],
  [1, -7, 9],
  [3, 3, 7], 
  [0, 5, 12]])

# допишите код здесь
print("Произведение Za:")
print(Z @ a.reshape(4, 1))
print()
print("Произведение CM:")
print(C @ M)
print()
print("Произведение a^TM:")
print(a.T.reshape(1,4) @ M)
print()
print("Произведение CZ:")
print(C @ Z)

Произведение Za:
[[ 20]
 [ 32]
 [-18]
 [ 14]]

Произведение CM:
[[ -6 -44  50]
 [ 31 -80 -22]
 [  4 109  87]
 [ 20  15 137]]

Произведение a^TM:
[[ 16 174  60]]

Произведение CZ:
[[ 14  26  -6  44]
 [  5  61 101   4]
 [ 13  29 -81  52]
 [ 23 103   5  76]]
