In [1]:
import numpy as np

In [2]:
a = np.array([
    [14, -8],
    [2, 3]
])
det = np.linalg.det(a)
print("Матрица:")
print(a)
print("Определитель:")
print(det) 

Матрица:
[[14 -8]
 [ 2  3]]
Определитель:
57.999999999999986


##### КР

In [2]:
a = np.array([
    [3.4, 0.9],
    [2.7, -0.1]
])
det = np.linalg.det(a)
print("Матрица:")
print(a)
print("Определитель:")
print(det) 

Матрица:
[[ 3.4  0.9]
 [ 2.7 -0.1]]
Определитель:
-2.77


In [4]:
a = np.array([
    [-3, 0, 5],
    [-2, 1, 8],
    [-9, 6, 3]
])
det = np.linalg.det(a)
print("Матрица:")
print(a)
print("Определитель:")
print(det) 

Матрица:
[[-3  0  5]
 [-2  1  8]
 [-9  6  3]]
Определитель:
120.00000000000009
