In [3]:
import numpy as np

In [4]:
#каждая строка в отдельных квадртаных скобках
m = np.array([
      [2, 17, 43],
      [36, 8, 4],
      [10, -11, 6],
      [3, 7, 15]
    ])
print(m)

[[  2  17  43]
 [ 36   8   4]
 [ 10 -11   6]
 [  3   7  15]]


In [5]:
#вектор столбец
k = np.array([
    [1],
    [14],
    [6],
    [9]
    ])
print(k) 

[[ 1]
 [14]
 [ 6]
 [ 9]]


In [6]:
#транспонироание матриц
m = np.array([
    [2, 17, 43],
    [36, 8, 4],
    [10, -11, 6],
    [3, 7, 15]
    ])

print("Матрица:")
print(m)  # Вывод исходной матрицы.
print()  # Пустая строка для разделения.
m = m.T  # Теперь m - это транспонированная матрица.
print("Транспонированная матрица:")
print(m)  # Вывод новой, транспонированной матрицы. 

Матрица:
[[  2  17  43]
 [ 36   8   4]
 [ 10 -11   6]
 [  3   7  15]]

Транспонированная матрица:
[[  2  36  10   3]
 [ 17   8 -11   7]
 [ 43   4   6  15]]
