умножение происходит строка - на столбец. AB != BA. Кол-во столбцов A == кол-во строк B

In [2]:
import numpy as np



In [3]:
W = np.array([
    [-15, 2, 0, 4],
    [-8, 1, 10, 5], 
    [6, 9, -4, 3],
    [-1, 5, 21, 6]
])

K = np.array([
    [0, -5, 1, 3],
  [0, 2, 4, 0],
  [-15, 3, 7, 2],
  [9, -6, 3, 12]
])

Y = np.array([
    [9, -7],
  [2, 31], 
  [0, 4], 
  [-1, -6]
])

In [4]:
print("Произведение WK:")
print(W @ K)
print()
print("Произведение YW:")
print('no')
print()
print("Произведение KY:")
print(K @ Y)
print()
print("Произведение KW:")
print(K @ W)

Произведение WK:
[[  36   55    5    3]
 [-105   42   81   56]
 [  87  -42   23   46]
 [-261   42  184  111]]

Произведение YW:
no

Произведение KY:
[[ -13 -169]
 [   4   78]
 [-131  214]
 [  57 -309]]

Произведение KW:
[[ 43  19   9  -4]
 [  8  38   4  22]
 [241  46  44 -12]
 [-81  99 180  87]]
