In [1]:
import numpy as np

##### шаг 1 - проверить, что кол-во строк и столбцов совпадает

In [2]:
d = np.array([11, -6])
h = np.array([-10, 0, 29])
R = np.array([
    [2, 18, 7],
    [-5, 4, 8]
])

In [7]:
h.shape

(3,)

In [5]:
R.shape

(2, 3)

##### шаг 2 Записать вектор в матрицу

In [9]:
h.reshape(3,1)

array([[-10],
       [  0],
       [ 29]])

##### шаг 3 умножить

In [15]:
R @ h.reshape(3,1)

array([[183],
       [282]])

##### если размероность не совпадает, то преобразуем матрицу

In [16]:
d.shape

(2,)

In [21]:
R.reshape(3,2) @ d

array([-86, 107,  -4])